[package]
name = "hacky_widget"
version = "0.1.0"
authors = ["Nick Senger <dev@nsenger.com>"]
edition = "2021"
publish = false

[dependencies]
iced.workspace = true
iced_wgpu.workspace = true
vanilla_iced.workspace = true
web-time = "1"
