[package]
name = "single_frame"
version = "0.1.0"
authors = ["Nick Senger <dev@nsenger.com>"]
edition = "2021"
publish = false

[dependencies]
bincode = "1.3"
iced.workspace = true
serde = { version = "1.0", features = ["derive"] }
vanilla_iced.workspace = true
